# Generated by Django 3.2.4 on 2021-06-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursoProducto', '0002_remove_nota_identificador_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='fecha_finalizacion',
            field=models.DateField(verbose_name='Fecha de Finalización'),
        ),
    ]
